#!/usr/bin/env bash
# Container entrypoint: make the volumes ready, then hand over to DSH.
#
# The order matters. The knowledge base is seeded and indexed first, because DSH starts the
# Sedna plugin at boot and a plugin pointing at a base with no index answers
# "no_applicable_knowledge" for everything -- a silent, convincing nothing that looks like
# the base has never heard of the topic.
set -euo pipefail

log() { printf '[entrypoint] %s\n' "$*" >&2; }

# 1. The knowledge base: seed only into empty, rebuild the index only when missing or poisoned.
/opt/sedna/bootstrap-kb.sh

# 2. The host composition patch (where the bind-all row for the web GUI lives) and the
#    settings file are written once, on a fresh volume, and never overwritten: they are the
#    operator's after that, and a `docker compose pull` must not undo their edits.
DSH_HOME="${DSH_HOME:-/home/dsh/.dsh}"
mkdir -p "$DSH_HOME"

if [[ ! -f "$DSH_HOME/cordis.patch.yml" ]]; then
    log "writing $DSH_HOME/cordis.patch.yml (binds the GUI to every interface *inside* the container)"
    cp /opt/sedna/cordis.patch.yml "$DSH_HOME/cordis.patch.yml"
fi

# 3. The model route. Generated from the same variables the rest of the stack uses, so the
#    stack cannot hold two opinions about which provider it is talking to.
if [[ ! -f "$DSH_HOME/settings.yaml" ]]; then
    if [[ -n "${LLM_BASE_URL:-}" || -n "${OLLAMA_API_KEY:-}" ]]; then
        base="${LLM_BASE_URL:-https://ollama.com/v1}"
        model="${LLM_MODEL:-gpt-oss:120b}"
        log "writing $DSH_HOME/settings.yaml: OpenAI-compatible route at $base, model $model"
        cat >"$DSH_HOME/settings.yaml" <<YAML
# Generated by the stack from compose/.env. Edit freely: this file is yours from now on,
# and the entrypoint will not write it again.
llm-pi-ai:
  providers:
    stack-provider:
      api: openai-completions
      baseURL: ${base}
      apiKeyEnv: OLLAMA_API_KEY
      displayName: Configured by compose/.env
      models:
        - id: ${model}
          name: ${model}
          contextWindow: 131072
          maxTokens: 32768
YAML
    else
        log "no model configured (LLM_BASE_URL and LLM_API_KEY are empty):"
        log "  DSH starts and the Sedna tools work, but no agent route exists yet."
        log "  Set them in compose/.env and restart, or edit $DSH_HOME/settings.yaml."
    fi
fi

log "starting DSH; the authenticated URL is printed in these logs (it carries a one-time token)"
# --no-open: there is no browser in a container, and the token URL is in the log instead.
exec dsh web --no-open --port "${DSH_PORT:-3080}"
