#!/usr/bin/env bash
# Keep the memory in this repository up to date.
#
# This is the "always updated backup" half of the objective, and it is deliberately
# conservative: it regenerates the seed, runs the gate, and then *proposes* the
# result on a branch.  It never pushes to the default branch, and it does not run
# until a human looks at what it produced -- a seed is data, and data that leaves a
# pentest machine deserves a review before it becomes public.
#
# Wiring (see docs/maintenance.md):
#   systemd --user timer  sedna-seed-refresh.timer  ->  this script
#
# Usage:
#   tools/refresh-seed.sh [--push] [--branch NAME] [--remote origin] [--dry-run]
#
# Without --push it regenerates the seed in place and reports; with --push it
# commits on a fresh branch, pushes it, and opens a pull request when `gh` is
# available (otherwise it prints the URL to open by hand).
set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/.." && pwd)"
cd "$repo"

push="false"
branch=""
remote="origin"
dry="false"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --push) push="true"; shift ;;
        --branch) branch="$2"; shift 2 ;;
        --remote) remote="$2"; shift 2 ;;
        --dry-run) dry="true"; shift ;;
        -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
        *) echo "refresh-seed: unknown argument: $1" >&2; exit 2 ;;
    esac
done

log() { printf '[refresh-seed] %s\n' "$*"; }
die() { printf '[refresh-seed] ERROR: %s\n' "$*" >&2; exit 1; }

[[ -z "$(git status --porcelain)" ]] || die "the working tree is dirty: commit or stash before refreshing the seed"

if [[ "$dry" == "true" ]]; then
    "$repo/tools/snapshot-seed.sh" --dry-run
    log "dry run: nothing changed"
    exit 0
fi

# 1. regenerate: the snapshot script stages, verifies, and only then publishes
"$repo/tools/snapshot-seed.sh" || die "snapshot-seed refused to produce a seed"

# 2. the manifest must describe exactly what is on disk
python3 "$repo/tools/verify-manifest.py" seed || die "the manifest does not match the artifacts"

# 3. nothing to do?
if [[ -z "$(git status --porcelain -- seed)" ]]; then
    log "the seed is already up to date; nothing to propose"
    exit 0
fi

log "seed changed:"
git status --porcelain -- seed | sed 's/^/    /'

if [[ "$push" != "true" ]]; then
    log "not pushing (pass --push to propose this on a branch)"
    exit 0
fi

# 4. propose on a branch, never on the default one
[[ -n "$branch" ]] || branch="seed/refresh-$(date -u +%Y%m%d)"
git checkout -b "$branch" >/dev/null 2>&1 || git checkout "$branch" >/dev/null 2>&1 \
    || die "cannot create or switch to branch $branch"

git add seed
git commit -q -m "seed: refresh $(date -u +%Y-%m-%dT%H:%MZ)

Regenerated by tools/refresh-seed.sh from the live memory on $(hostname -s 2>/dev/null || echo this machine).
Artifacts and hashes are in seed/SEED-MANIFEST.json; anything removed before publication
is listed, masked, in seed/REDACTION-REPORT.md.

This is data, not source: review before merging." || die "commit failed"

git push -u "$remote" "$branch" || die "push failed"

if command -v gh >/dev/null 2>&1; then
    gh pr create --fill --title "seed: refresh $(date -u +%Y-%m-%d)" \
        --body "Automated seed refresh. The gate (tools/verify-seed.sh) passed locally; CI will re-run it on this branch." \
        && log "pull request opened"
else
    log "gh is not installed: open the pull request yourself from the pushed branch '$branch'"
fi
